# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🐞 Bug Report
description: File a report for unexpected or undesired behavior.
title: "<brief summary of what bug or error was observed>"
labels: ["type: bug"]
type: "bug"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve! 🙏 Please answer these questions and provide as much information as possible about your problem.
  
  - id: preamble
    type: checkboxes
    attributes:
      label: Pre-reqs
      description: |
        Please run through the following list and make sure you've tried the usual "quick fixes":
        - Search the [current open issues](https://github.com/gemini-cli-extensions/postgres/issues)
        - Update to the latest version of the extension and [Gemini CLI](https://github.com/google-gemini/gemini-cli?tab=readme-ov-file#stable)
      options: 
        - label: "I've searched the current open issues"
          required: true
        - label: "I've updated to the latest versions"

  - type: input
    id: ex_version
    attributes:
      label: Extension Version
      description: |
        What version of the extension are you using (`gemini extensions list` or `/extensions list`)?
      placeholder: ex. version 0.1.0 
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Gemini CLI Version
      description: |
        What version of the Gemini CLI are you using (`gemini --version`)?
      placeholder: ex. version 0.6.0 
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Let us know what OS type and version in which you are seeing the bug!"
      placeholder: output of `uname -a`
    validations:
      required: true

  - id: current-behavior
    type: textarea
    attributes:
      label: Current Behavior
      description: "Please enter a detailed description of the behavior you encountered instead."
    validations:
      required: true

  - id: expected-behavior
    type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Please enter a detailed description of the behavior you expected, and any information about what behavior you 
        noticed and why it is defective or unintentional.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce?
      description: |
        How can we reproduce this bug? Please walk us through it step by step,
        with as much relevant detail as possible. A 'minimal' reproduction is
        preferred, which means removing as much of the examples as possible so
        only the minimum required to run and reproduce the bug is left. 
      value: |
        1. ?
        2. ?
        3. ?
        ...
    validations:
      required: true

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: |
        Any other information you want us to know?
